name: Lint & Format Code

on:
  workflow_dispatch: ~
  push:
    paths:
      - "**/*.js"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/check_code.yml"
    branches:
      - "master"
  pull_request:
    paths:
      - "**/*.js"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/check_code.yml"

jobs:
  Check-Code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check format
        run: pnpm test
