name: Get Game Version # yml文件名
 
on:
  workflow_dispatch: ~
  push:
    branches:
      - master
  schedule:   
    - cron: '1-10 11 * * 1' # 每周一上午11点1分到11点10分运行
    - cron: '*/10 9-11 * * 2' # 每周二上午9点到11点，每10分钟运行一次
    - cron: '*/10 6-11 * * 3' # 每周三上午6点到11点，每10分钟运行一次
    - cron: '*/10 4-11 * * 4' # 每周四上午4点到11点，每10分钟运行一次
    - cron: '*/10 6-13 * * 5' # 每周五上午6点到13点，每10分钟运行一次
    - cron: '* */2 * * *'   # 每两小时运行一次
 
jobs:
  get-Game-Version: # 任务名
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v6
          with:
            fetch-depth: 0
        - name: Install Node.js
          uses: actions/setup-node@v6
          with:
            node-version: 20
        - name: Install pnpm
          uses: pnpm/action-setup@v6
          with:
            version: 9
        - name: Install dependencies
          run: pnpm install
        - name: Extract branch name
          shell: bash
          run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          id: extract_branch
        - name: Check GI Win Game CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_GI: ${{ secrets.TGMsgID_GI }}
          run: node ./Scripts/getWinGameVersion.js gi cn
        - name: Check GI Win Game OS Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_GI: ${{ secrets.TGMsgID_GI }}
          run: node ./Scripts/getWinGameVersion.js gi os
        - name: Check GI Win Launcher CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_GI: ${{ secrets.TGMsgID_GI }}
          run: node ./Scripts/getWinLauncherVersion.js gi cn
        - name: Check GI Win Launcher OS Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_GI: ${{ secrets.TGMsgID_GI }}
          run: node ./Scripts/getWinLauncherVersion.js gi os
        - name: Check GI Android Game CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_GI: ${{ secrets.TGMsgID_GI }}
          run: node ./Scripts/getAndroidGameVersion.js gi
        - name: Check SR Win Game CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_SR: ${{ secrets.TGMsgID_SR }}
          run: node ./Scripts/getWinGameVersion.js sr cn
        - name: Check SR Win Game OS Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_SR: ${{ secrets.TGMsgID_SR }}
          run: node ./Scripts/getWinGameVersion.js sr os
        - name: Check SR Win Launcher CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_SR: ${{ secrets.TGMsgID_SR }}
          run: node ./Scripts/getWinLauncherVersion.js sr cn
        - name: Check SR Win Launcher OS Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_SR: ${{ secrets.TGMsgID_SR }}
          run: node ./Scripts/getWinLauncherVersion.js sr os
        - name: Check SR Android Game CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_SR: ${{ secrets.TGMsgID_SR }}
          run: node ./Scripts/getAndroidGameVersion.js sr
        - name: Check WW Win Launcher CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
          run: node ./Scripts/getWWWinLauncherVersion.js cn
        - name: Check WW Win Launcher OS Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
          run: node ./Scripts/getWWWinLauncherVersion.js os
        - name: Check WW Win Game CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
          run: node ./Scripts/getWWWinGameVersion.js cn
        - name: Check WW Win Game OS Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
          run: node ./Scripts/getWWWinGameVersion.js os
        - name: Check WW Android Game CN Update
          env: 
            TGBotToken: ${{ secrets.TGBotToken }}
            TGMsgID: ${{ secrets.TGMsgID }}
            TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
          run: node ./Scripts/getAndroidGameVersion.js ww
        # 旧的灰度域名停用了, 暂时抓不到也猜不到新的灰度 url , 先停用这个
        # - name: Check WW Win Launcher CN Gray Update
        #   env: 
        #     TGBotToken: ${{ secrets.TGBotToken }}
        #     TGMsgID: ${{ secrets.TGMsgID }}
        #     TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
        #   run: node ./Scripts/getWWWinLauncherVersion.js cn new
        # - name: Check WW Win Launcher OS Gray Update
        #   env: 
        #     TGBotToken: ${{ secrets.TGBotToken }}
        #     TGMsgID: ${{ secrets.TGMsgID }}
        #     TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
        #   run: node ./Scripts/getWWWinLauncherVersion.js os new
        # - name: Check WW Win Game CN Gray Update
        #   env: 
        #     TGBotToken: ${{ secrets.TGBotToken }}
        #     TGMsgID: ${{ secrets.TGMsgID }}
        #     TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
        #   run: node ./Scripts/getWWWinGameVersion.js cn new
        # - name: Check WW Win Game OS Gray Update
        #   env: 
        #     TGBotToken: ${{ secrets.TGBotToken }}
        #     TGMsgID: ${{ secrets.TGMsgID }}
        #     TGMsgID_WW: ${{ secrets.TGMsgID_WW }}
        #   run: node ./Scripts/getWWWinGameVersion.js os new
        - run: git config --global user.name "github-actions"
        - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        - run: git checkout -- pnpm-lock.yaml
        - run: git stash
        - run: git checkout ${{ steps.extract_branch.outputs.branch }} && git pull
        - run: git stash pop || true

        - name: Commit code changes
          run: "git add . && git commit -m 'docs: update game version [skip ci]' || true"
        - name: Push code changes
          run: git push --set-upstream --force origin ${{ steps.extract_branch.outputs.branch }}
